# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.

# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

import math
import warnings

import torch
from torch import nn

from sparse.module.spatial_sparse_attention import (
    SpatialSparseAttentionIn,
    SpatialSparseAttentionMid,
    SpatialSparseAttentionOut,
)
from models_sparse.seqparallel_utils import all_gather_tokens, all_gather_tokens_checkpointed


class LayerNorm32(nn.LayerNorm):
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return super().forward(x.float()).type(x.dtype)


def zero_module(module):
    for p in module.parameters():
        nn.init.zeros_(p)
    return module


def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1.0 + math.erf(x / math.sqrt(2.0))) / 2.0

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn(
            "mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
            "The distribution of values may be incorrect.",
            stacklevel=2,
        )

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.0))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(
    tensor: torch.Tensor,
    mean: float = 0.0,
    std: float = 1.0,
    a: float = -2.0,
    b: float = 2.0,
) -> torch.Tensor:
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


class Mlp(nn.Module):
    def __init__(
        self,
        in_features,
        hidden_features=None,
        out_features=None,
        act_layer=nn.GELU,
        bias=True,
        use_weight_norm=False,
    ):
        super().__init__()
        out_features = out_features or in_features
        hidden_features = hidden_features or in_features
        self.fc1 = nn.Linear(in_features, hidden_features, bias=bias)
        self.act = act_layer()
        self.fc2 = nn.Linear(hidden_features, out_features, bias=bias)

        if use_weight_norm:
            self.fc1 = nn.utils.parametrizations.weight_norm(self.fc1)
            self.fc2 = nn.utils.parametrizations.weight_norm(self.fc2)

    def forward(self, x):
        x = self.fc1(x)
        x = self.act(x)
        x = self.fc2(x)
        return x


class CrossAttention(nn.Module):
    def __init__(
        self,
        dim,
        num_q_heads=32,
        num_kv_heads=2,
        qkv_bias=False,
        use_weight_norm=False,
        oneside=False,
        topk_volume=8,
        topk_multiimage=2,
        use_sequence_parallel=False,
        no_checkpoint_all_gather=False,
    ):
        super().__init__()
        self.num_q_heads = num_q_heads
        self.num_kv_heads = num_kv_heads
        self.dim = dim
        self.head_dim = dim // num_q_heads

        self.q_proj_x = nn.Linear(dim, dim, bias=qkv_bias)
        self.k_proj_x = nn.Linear(dim, self.head_dim * self.num_kv_heads, bias=qkv_bias)
        self.v_proj_x = nn.Linear(dim, self.head_dim * self.num_kv_heads, bias=qkv_bias)
        self.gate_x = nn.Sequential(nn.Linear(dim, 2 * dim), nn.Sigmoid())
        self.proj_x = nn.Linear(dim, dim)
        self.norm_layer_q = LayerNorm32(self.head_dim, elementwise_affine=False)
        self.norm_layer_kv = LayerNorm32(self.head_dim, elementwise_affine=False)
        self.use_sequence_parallel = use_sequence_parallel
        self.no_checkpoint_all_gather = no_checkpoint_all_gather

        self.topk_volume = topk_volume
        self.topk_multiimage = topk_multiimage

        # Compress tokens
        self.x_2_x_attn_in = SpatialSparseAttentionIn(
            head_dim=dim // num_q_heads,
            num_kv_heads=num_kv_heads,
        )
        self.x_2_y_attn_in = SpatialSparseAttentionIn(
            head_dim=dim // num_q_heads,
            num_kv_heads=num_kv_heads,
        )

        # Compute attention
        self.x_2_x_attn_mid = SpatialSparseAttentionMid(
            hidden_dim=dim,
            num_q_heads=num_q_heads,
            num_kv_heads=num_kv_heads,
            is_window_attn=True,
        )
        self.x_2_y_attn_mid = SpatialSparseAttentionMid(
            hidden_dim=dim,
            num_q_heads=num_q_heads,
            num_kv_heads=num_kv_heads,
            is_window_attn=False,
        )

        # Fuse 3 / 2 kinds of attention
        self.x_2_x_attn_out = SpatialSparseAttentionOut(
            hidden_dim=dim,
            num_q_heads=num_q_heads,
            num_kv_heads=num_kv_heads,
            is_window_attn=True,
        )
        self.x_2_y_attn_out = SpatialSparseAttentionOut(
            hidden_dim=dim,
            num_q_heads=num_q_heads,
            num_kv_heads=num_kv_heads,
            is_window_attn=False,
        )

        self.oneside = oneside
        self.k_proj_y = nn.Linear(dim, self.head_dim * self.num_kv_heads, bias=qkv_bias)
        self.v_proj_y = nn.Linear(dim, self.head_dim * self.num_kv_heads, bias=qkv_bias)

        if not self.oneside:
            self.q_proj_y = nn.Linear(dim, dim, bias=qkv_bias)
            self.gate_y = nn.Sequential(
                nn.Linear(dim, 2 * dim, bias=False), nn.Sigmoid()
            )
            self.proj_y = nn.Linear(dim, dim)

            # Compress tokens
            self.y_2_y_attn_in = SpatialSparseAttentionIn(
                head_dim=dim // num_q_heads,
                num_kv_heads=num_kv_heads,
            )
            self.y_2_x_attn_in = SpatialSparseAttentionIn(
                head_dim=dim // num_q_heads,
                num_kv_heads=num_kv_heads,
            )

            # Compute attention
            self.y_2_y_attn_mid = SpatialSparseAttentionMid(
                hidden_dim=dim,
                num_q_heads=num_q_heads,
                num_kv_heads=num_kv_heads,
                is_window_attn=True,
            )
            self.y_2_x_attn_mid = SpatialSparseAttentionMid(
                hidden_dim=dim,
                num_q_heads=num_q_heads,
                num_kv_heads=num_kv_heads,
                is_window_attn=False,
            )

            # Fuse 3 / 2 kinds of attention
            self.y_2_y_attn_out = SpatialSparseAttentionOut(
                hidden_dim=dim,
                num_q_heads=num_q_heads,
                num_kv_heads=num_kv_heads,
                is_window_attn=True,
            )
            self.y_2_x_attn_out = SpatialSparseAttentionOut(
                hidden_dim=dim,
                num_q_heads=num_q_heads,
                num_kv_heads=num_kv_heads,
                is_window_attn=False,
            )

        if use_weight_norm:
            self.q_proj_x = nn.utils.parametrizations.weight_norm(self.q_proj_x)
            self.k_proj_x = nn.utils.parametrizations.weight_norm(self.k_proj_x)
            self.v_proj_x = nn.utils.parametrizations.weight_norm(self.v_proj_x)
            self.proj_x = nn.utils.parametrizations.weight_norm(self.proj_x)
            self.k_proj_y = nn.utils.parametrizations.weight_norm(self.k_proj_y)
            self.v_proj_y = nn.utils.parametrizations.weight_norm(self.v_proj_y)
            if not self.oneside:
                self.q_proj_y = nn.utils.parametrizations.weight_norm(self.q_proj_y)
                self.proj_y = nn.utils.parametrizations.weight_norm(self.proj_y)

    def _normalize_qkv(self, q, k, compressed_k):
        """
        Normalize q, k, compressed_k tensors BEFORE all_gather.
        This is more memory efficient because we normalize on local tensors
        (N/num_gpus tokens) instead of full gathered sequence (N tokens).

        Args:
            q: [local_tokens, dim] - query tensor (dim = num_q_heads * head_dim)
            k: [local_tokens, kv_dim] - key tensor (kv_dim = num_kv_heads * head_dim)
            compressed_k: [local_blocks, kv_dim] - compressed key tensor

        Returns:
            Normalized tensors with same 2D shapes (compatible with all_gather)
        """
        # Reshape to 3D, normalize over head_dim, reshape back to 2D
        # q: [N, dim] -> [N, num_q_heads, head_dim] -> normalize -> [N, dim]
        q_3d = q.view(-1, self.num_q_heads, self.head_dim)
        q_normed = self.norm_layer_q(q_3d)
        q = q_normed.view(-1, self.dim).contiguous()

        # k: [N, kv_dim] -> [N, num_kv_heads, head_dim] -> normalize -> [N, kv_dim]
        kv_dim = self.head_dim * self.num_kv_heads
        k_3d = k.view(-1, self.num_kv_heads, self.head_dim)
        k_normed = self.norm_layer_kv(k_3d)
        k = k_normed.view(-1, kv_dim).contiguous()

        # compressed_k: [M, kv_dim] -> [M, num_kv_heads, head_dim] -> normalize -> [M, kv_dim]
        ck_3d = compressed_k.view(-1, self.num_kv_heads, self.head_dim)
        ck_normed = self.norm_layer_kv(ck_3d)
        compressed_k = ck_normed.view(-1, kv_dim).contiguous()

        return q, k, compressed_k

    def forward(self, x, cu_seqlens_x, y, cu_seqlens_y, im_num, attn_map):
        # Compute q_x, k_x, v_x
        q_x = self.q_proj_x(x)
        k_x = self.k_proj_x(x)
        v_x = self.v_proj_x(x)

        # Compute q_y, k_y, v_y
        k_y = self.k_proj_y(y)
        v_y = self.v_proj_y(y)
        if not self.oneside:
            q_y = self.q_proj_y(y)

        compressed_k_x_2_x, compressed_v_x_2_x = self.x_2_x_attn_in(
            k_x, v_x, attn_map["vol_to_vol_attn"]
        )
        compressed_k_x_2_y, compressed_v_x_2_y = self.x_2_y_attn_in(
            k_y, v_y, attn_map["vol_to_img_attn"]
        )
        if not self.oneside:
            compressed_k_y_2_y, compressed_v_y_2_y = self.y_2_y_attn_in(
                k_y, v_y, attn_map["img_to_img_attn"]
            )
            compressed_k_y_2_x, compressed_v_y_2_x = self.y_2_x_attn_in(
                k_x, v_x, attn_map["img_to_vol_attn"]
            )

        # Normalize q, k, compressed_k BEFORE all_gather
        # This is more memory efficient: normalize on local tensors (N/num_gpus)
        # instead of full gathered sequence (N tokens). Saves ~2GB memory.
        q_x, k_x, compressed_k_x_2_x = self._normalize_qkv(q_x, k_x, compressed_k_x_2_x)
        # For x_2_y: q=q_x (already normalized), k=k_y, compressed_k=compressed_k_x_2_y
        # We need to normalize k_y and compressed_k_x_2_y separately
        kv_dim = self.head_dim * self.num_kv_heads
        k_y_3d = k_y.view(-1, self.num_kv_heads, self.head_dim)
        k_y = self.norm_layer_kv(k_y_3d).view(-1, kv_dim).contiguous()
        ck_x_2_y_3d = compressed_k_x_2_y.view(-1, self.num_kv_heads, self.head_dim)
        compressed_k_x_2_y = (
            self.norm_layer_kv(ck_x_2_y_3d).view(-1, kv_dim).contiguous()
        )

        if not self.oneside:
            # Normalize q_y
            q_y_3d = q_y.view(-1, self.num_q_heads, self.head_dim)
            q_y = self.norm_layer_q(q_y_3d).view(-1, self.dim).contiguous()
            # Normalize compressed_k for y_2_y and y_2_x
            ck_y_2_y_3d = compressed_k_y_2_y.view(-1, self.num_kv_heads, self.head_dim)
            compressed_k_y_2_y = (
                self.norm_layer_kv(ck_y_2_y_3d).view(-1, kv_dim).contiguous()
            )
            ck_y_2_x_3d = compressed_k_y_2_x.view(-1, self.num_kv_heads, self.head_dim)
            compressed_k_y_2_x = (
                self.norm_layer_kv(ck_y_2_x_3d).view(-1, kv_dim).contiguous()
            )

        if self.use_sequence_parallel:
            # All-gather kv and compressed_kv for compressed attention and selection attention
            # After all_gather, each GPU has ALL kv tokens but only LOCAL q tokens
            # Window attention will still use local kv (k_x, v_x, k_y, v_y)

            # Get gather sizes from attn_map which were computed in seq_parallel_token_blocks:
            # - vol_gather_sizes / img_gather_sizes: token counts per rank after redistribution
            # - vol_compressed_gather_sizes / img_compressed_gather_sizes: block counts per rank
            vol_gather_sizes = attn_map["vol_gather_sizes"]
            img_gather_sizes = attn_map["img_gather_sizes"]
            vol_compressed_gather_sizes = attn_map["vol_compressed_gather_sizes"]
            img_compressed_gather_sizes = attn_map["img_compressed_gather_sizes"]

            # Select all_gather function based on checkpoint setting
            # Checkpointing trades extra communication for memory savings (~3GB for 400K tokens)
            _all_gather_fn = (
                all_gather_tokens_checkpointed
                if not self.no_checkpoint_all_gather
                else all_gather_tokens
            )

            # Fused all-gather for volume tokens (k_x, v_x)
            # Reduces 2 all-gather calls to 1
            kv_x_dim = k_x.shape[-1]
            fused_kv_x = torch.cat([k_x, v_x], dim=-1)
            global_fused_kv_x = _all_gather_fn(
                fused_kv_x, gather_sizes=vol_gather_sizes
            )
            global_k_x, global_v_x = global_fused_kv_x.split(
                [kv_x_dim, kv_x_dim], dim=-1
            )
            # Free fused tensor after splitting (saves ~2 * kv_x_dim * N bytes)
            del fused_kv_x, global_fused_kv_x

            # Fused all-gather for image tokens (k_y, v_y)
            # Reduces 2 all-gather calls to 1
            kv_y_dim = k_y.shape[-1]
            fused_kv_y = torch.cat([k_y, v_y], dim=-1)
            global_fused_kv_y = _all_gather_fn(
                fused_kv_y, gather_sizes=img_gather_sizes
            )
            global_k_y, global_v_y = global_fused_kv_y.split(
                [kv_y_dim, kv_y_dim], dim=-1
            )
            # Free fused tensor after splitting (saves ~2 * kv_y_dim * N bytes)
            del fused_kv_y, global_fused_kv_y

            # Fused all-gather for vol compressed kv
            # Groups: compressed_k_x_2_x, compressed_v_x_2_x, and if not oneside: compressed_k_y_2_x, compressed_v_y_2_x
            compressed_kv_vol_dim = compressed_k_x_2_x.shape[-1]
            if not self.oneside:
                # Fuse 4 tensors: reduces 4 all-gather calls to 1
                fused_compressed_kv_vol = torch.cat(
                    [
                        compressed_k_x_2_x,
                        compressed_v_x_2_x,
                        compressed_k_y_2_x,
                        compressed_v_y_2_x,
                    ],
                    dim=-1,
                )
                # Free local compressed tensors before all-gather
                # (only global versions needed for attn_mid)
                del compressed_k_x_2_x, compressed_v_x_2_x
                del compressed_k_y_2_x, compressed_v_y_2_x

                global_fused_compressed_kv_vol = _all_gather_fn(
                    fused_compressed_kv_vol, gather_sizes=vol_compressed_gather_sizes
                )
                (
                    global_compressed_k_x_2_x,
                    global_compressed_v_x_2_x,
                    global_compressed_k_y_2_x,
                    global_compressed_v_y_2_x,
                ) = global_fused_compressed_kv_vol.split(
                    [compressed_kv_vol_dim] * 4, dim=-1
                )
                # Free fused tensor after splitting
                del fused_compressed_kv_vol, global_fused_compressed_kv_vol
            else:
                # Fuse 2 tensors: reduces 2 all-gather calls to 1
                fused_compressed_kv_vol = torch.cat(
                    [compressed_k_x_2_x, compressed_v_x_2_x], dim=-1
                )
                # Free local compressed tensors before all-gather
                del compressed_k_x_2_x, compressed_v_x_2_x

                global_fused_compressed_kv_vol = _all_gather_fn(
                    fused_compressed_kv_vol, gather_sizes=vol_compressed_gather_sizes
                )
                (
                    global_compressed_k_x_2_x,
                    global_compressed_v_x_2_x,
                ) = global_fused_compressed_kv_vol.split(
                    [compressed_kv_vol_dim] * 2, dim=-1
                )
                # Free fused tensor after splitting
                del fused_compressed_kv_vol, global_fused_compressed_kv_vol

            # Fused all-gather for img compressed kv
            # Groups: compressed_k_x_2_y, compressed_v_x_2_y, and if not oneside: compressed_k_y_2_y, compressed_v_y_2_y
            compressed_kv_img_dim = compressed_k_x_2_y.shape[-1]
            if not self.oneside:
                # Fuse 4 tensors: reduces 4 all-gather calls to 1
                fused_compressed_kv_img = torch.cat(
                    [
                        compressed_k_x_2_y,
                        compressed_v_x_2_y,
                        compressed_k_y_2_y,
                        compressed_v_y_2_y,
                    ],
                    dim=-1,
                )
                # Free local compressed tensors before all-gather
                del compressed_k_x_2_y, compressed_v_x_2_y
                del compressed_k_y_2_y, compressed_v_y_2_y

                global_fused_compressed_kv_img = _all_gather_fn(
                    fused_compressed_kv_img, gather_sizes=img_compressed_gather_sizes
                )
                (
                    global_compressed_k_x_2_y,
                    global_compressed_v_x_2_y,
                    global_compressed_k_y_2_y,
                    global_compressed_v_y_2_y,
                ) = global_fused_compressed_kv_img.split(
                    [compressed_kv_img_dim] * 4, dim=-1
                )
                # Free fused tensor after splitting
                del fused_compressed_kv_img, global_fused_compressed_kv_img
            else:
                # Fuse 2 tensors: reduces 2 all-gather calls to 1
                fused_compressed_kv_img = torch.cat(
                    [compressed_k_x_2_y, compressed_v_x_2_y], dim=-1
                )
                # Free local compressed tensors before all-gather
                del compressed_k_x_2_y, compressed_v_x_2_y

                global_fused_compressed_kv_img = _all_gather_fn(
                    fused_compressed_kv_img, gather_sizes=img_compressed_gather_sizes
                )
                (
                    global_compressed_k_x_2_y,
                    global_compressed_v_x_2_y,
                ) = global_fused_compressed_kv_img.split(
                    [compressed_kv_img_dim] * 2, dim=-1
                )
                # Free fused tensor after splitting
                del fused_compressed_kv_img, global_fused_compressed_kv_img
        else:
            global_k_x = k_x
            global_v_x = v_x
            global_k_y = k_y
            global_v_y = v_y
            global_compressed_k_x_2_x = compressed_k_x_2_x
            global_compressed_v_x_2_x = compressed_v_x_2_x
            global_compressed_k_x_2_y = compressed_k_x_2_y
            global_compressed_v_x_2_y = compressed_v_x_2_y
            if not self.oneside:
                global_compressed_k_y_2_y = compressed_k_y_2_y
                global_compressed_v_y_2_y = compressed_v_y_2_y
                global_compressed_k_y_2_x = compressed_k_y_2_x
                global_compressed_v_y_2_x = compressed_v_y_2_x

        # Sparse attention kernel
        # Note: When using sequence parallel, cu_seqlens_x and cu_seqlens_y are already
        # the local_cu_seqlens (computed in voldecoder.py from seq_parallel_token_blocks),
        # which have entries for ALL batches across all GPUs but only count q tokens
        # on the current GPU.
        sparse_info = {}
        x_cross_output, vol_to_img_attn = self.x_2_y_attn_mid(
            q_x,
            cu_seqlens_x,
            global_k_y,
            global_compressed_k_x_2_y,
            global_v_y,
            global_compressed_v_x_2_y,
            self.topk_multiimage * im_num,
            attn_map["vol_to_img_attn"],
        )
        sparse_info["v_2_i"] = vol_to_img_attn

        x_self_output, vol_to_vol_attn = self.x_2_x_attn_mid(
            q_x,
            cu_seqlens_x,
            global_k_x,
            global_compressed_k_x_2_x,
            global_v_x,
            global_compressed_v_x_2_x,
            self.topk_volume,
            attn_map["vol_to_vol_attn"],
        )
        sparse_info["v_2_v"] = vol_to_vol_attn

        if not self.oneside:
            y_cross_output, img_to_vol_attn = self.y_2_x_attn_mid(
                q_y,
                cu_seqlens_y,
                global_k_x,
                global_compressed_k_y_2_x,
                global_v_x,
                global_compressed_v_y_2_x,
                self.topk_volume,
                attn_map["img_to_vol_attn"],
            )
            sparse_info["i_2_v"] = img_to_vol_attn

            y_self_output, img_to_img_attn = self.y_2_y_attn_mid(
                q_y,
                cu_seqlens_y,
                global_k_y,
                global_compressed_k_y_2_y,
                global_v_y,
                global_compressed_v_y_2_y,
                self.topk_multiimage * im_num,
                attn_map["img_to_img_attn"],
            )
            sparse_info["i_2_i"] = img_to_img_attn

        x_cross = self.x_2_y_attn_out(
            x, q_x, k_y, v_y, attn_map["vol_to_img_attn"], x_cross_output
        )
        x_self = self.x_2_x_attn_out(
            x, q_x, k_x, v_x, attn_map["vol_to_vol_attn"], x_self_output
        )
        if not self.oneside:
            y_cross = self.y_2_x_attn_out(
                y, q_y, k_x, v_x, attn_map["img_to_vol_attn"], y_cross_output
            )
            y_self = self.y_2_y_attn_out(
                y, q_y, k_y, v_y, attn_map["img_to_img_attn"], y_self_output
            )

        x_gate = self.gate_x(x)
        x_output = (
            x_cross * x_gate[:, 0 : self.dim]
            + x_self * x_gate[:, self.dim : self.dim * 2]
        )
        x = self.proj_x(x_output)
        if not self.oneside:
            y_gate = self.gate_y(y)
            y_output = (
                y_cross * y_gate[:, 0 : self.dim]
                + y_self * y_gate[:, self.dim : 2 * self.dim]
            )
            y = self.proj_y(y_output)
            return x, y, sparse_info
        else:
            return x, sparse_info


class BlockMix(nn.Module):
    def __init__(
        self,
        dim,
        num_q_heads=32,
        num_kv_heads=2,
        mlp_ratio=4.0,
        qkv_bias=False,
        act_layer=nn.GELU,
        norm_layer=LayerNorm32,
        use_weight_norm=False,
        topk_volume=8,
        topk_multiimage=2,
        use_sequence_parallel=False,
        no_checkpoint_all_gather=False,
    ):
        super().__init__()
        mlp_hidden_dim = int(dim * mlp_ratio)
        self.norm = norm_layer(dim, elementwise_affine=False)
        self.crs_attn = CrossAttention(
            dim,
            num_q_heads=num_q_heads,
            num_kv_heads=num_kv_heads,
            qkv_bias=qkv_bias,
            use_weight_norm=use_weight_norm,
            topk_volume=topk_volume,
            topk_multiimage=topk_multiimage,
            use_sequence_parallel=use_sequence_parallel,
            no_checkpoint_all_gather=no_checkpoint_all_gather,
        )
        self.mlp_x_1 = Mlp(
            in_features=dim,
            hidden_features=mlp_hidden_dim,
            act_layer=act_layer,
            use_weight_norm=use_weight_norm,
        )
        self.mlp_y_1 = Mlp(
            in_features=dim,
            hidden_features=mlp_hidden_dim,
            act_layer=act_layer,
            use_weight_norm=use_weight_norm,
        )

    def forward(
        self,
        x,
        cu_seqlens_x,
        y,
        cu_seqlens_y,
        attn_map,
        im_num,
    ):
        # Cross attention between x and y
        x = self.norm(x)
        y = self.norm(y)
        x_res, y_res, sparse_info = self.crs_attn(
            x,
            cu_seqlens_x,
            y,
            cu_seqlens_y,
            im_num,
            attn_map,
        )
        x = x + x_res
        x = self.norm(x)
        x = x + self.mlp_x_1(x)
        y = y + y_res
        y = self.norm(y)
        y = y + self.mlp_y_1(y)

        return x, y, sparse_info


class BlockMixOneside(nn.Module):
    def __init__(
        self,
        dim,
        num_q_heads=32,
        num_kv_heads=2,
        mlp_ratio=4.0,
        qkv_bias=False,
        act_layer=nn.GELU,
        norm_layer=LayerNorm32,
        use_weight_norm=False,
        topk_volume=8,
        topk_multiimage=2,
        use_sequence_parallel=False,
        no_checkpoint_all_gather=False,
    ):
        super().__init__()
        mlp_hidden_dim = int(dim * mlp_ratio)
        self.norm = norm_layer(dim, elementwise_affine=False)
        self.crs_attn = CrossAttention(
            dim,
            num_q_heads=num_q_heads,
            num_kv_heads=num_kv_heads,
            qkv_bias=qkv_bias,
            use_weight_norm=use_weight_norm,
            oneside=True,
            topk_volume=topk_volume,
            topk_multiimage=topk_multiimage,
            use_sequence_parallel=use_sequence_parallel,
            no_checkpoint_all_gather=no_checkpoint_all_gather,
        )
        self.mlp_x_1 = Mlp(
            in_features=dim,
            hidden_features=mlp_hidden_dim,
            act_layer=act_layer,
            use_weight_norm=use_weight_norm,
        )

    def forward(
        self,
        x,
        cu_seqlens_x,
        y,
        cu_seqlens_y,
        attn_map,
        im_num,
    ):
        # Cross attention between x and y
        x = self.norm(x)
        y = self.norm(y)
        x_res, sparse_info = self.crs_attn(
            x,
            cu_seqlens_x,
            y,
            cu_seqlens_y,
            im_num,
            attn_map,
        )
        x = x + x_res
        x = self.norm(x)
        x = x + self.mlp_x_1(x)

        return x, sparse_info
