name: lsrm-dev
channels:
    - conda-forge
dependencies:
    - python=3.10
    - pip
    - cuda-nvcc=12.1
    - cuda-cccl=12.1
    - gcc_linux-64=12
    - gxx_linux-64=12
    - pip:
        # Use the host's pip index configuration for PyTorch and its CUDA libraries.
        - torch==2.4.0
        - torchvision==0.19.0
        - torchaudio==2.4.0
        - fvcore
        - iopath
        - pytorch3d @ https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py310_cu121_pyt240/pytorch3d-0.7.8-cp310-cp310-linux_x86_64.whl
        - nerfacc==0.5.3
        - nvidia-cuda-nvcc-cu12
        - nvidia-cuda-cccl-cu12
        - nvidia-cuda-runtime-cu12
        - nvidia-cublas-cu12
        - nvidia-cusparse-cu12
        - nvidia-cusolver-cu12
        - nvidia-curand-cu12
        - nvidia-cufft-cu12
        - flash-attn @ https://github.com/Dao-AILab/flash-attention/releases/download/v2.5.9.post1/flash_attn-2.5.9.post1+cu122torch2.4cxx11abiFALSE-cp310-cp310-linux_x86_64.whl
        - numpy<2
        - trimesh
        - plyfile
        - einops
        - lpips
        - scikit-image
        - opencv-python
        - scipy
        - OpenEXR
        - ffmpeg-python
        - ninja
        - pyyaml
        - rich
        - timm
        - pillow
        - tqdm
        - matplotlib
        - intel-cmplr-lib-rt
