# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.

# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

import math
import warnings

import torch
from flash_attn import flash_attn_func
from torch import nn


def zero_module(module):
    for p in module.parameters():
        nn.init.zeros_(p)
    return module


def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1.0 + math.erf(x / math.sqrt(2.0))) / 2.0

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn(
            "mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
            "The distribution of values may be incorrect.",
            stacklevel=2,
        )

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.0))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(
    tensor: torch.Tensor,
    mean: float = 0.0,
    std: float = 1.0,
    a: float = -2.0,
    b: float = 2.0,
) -> torch.Tensor:
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


class Mlp(nn.Module):
    def __init__(
        self,
        in_features,
        hidden_features=None,
        out_features=None,
        act_layer=nn.GELU,
        bias=True,
        use_weight_norm=False,
    ):
        super().__init__()
        out_features = out_features or in_features
        hidden_features = hidden_features or in_features
        self.fc1 = nn.Linear(in_features, hidden_features, bias=bias)
        self.act = act_layer()
        self.fc2 = nn.Linear(hidden_features, out_features, bias=bias)

        if use_weight_norm:
            self.fc1 = nn.utils.parametrizations.weight_norm(self.fc1)
            self.fc2 = nn.utils.parametrizations.weight_norm(self.fc2)

    def forward(self, x):
        x = self.fc1(x)
        x = self.act(x)
        x = self.fc2(x)
        return x


class CrossAttention(nn.Module):
    def __init__(
        self,
        dim,
        num_q_heads=32,
        num_kv_heads=2,
        qkv_bias=False,
        use_weight_norm=False,
        norm_layer=nn.LayerNorm,
        oneside=False,
    ):
        super().__init__()
        self.num_q_heads = num_q_heads
        self.num_kv_heads = num_kv_heads
        self.dim = dim
        self.head_dim = dim // num_q_heads

        self.norm_layer = norm_layer(self.head_dim, elementwise_affine=False)

        self.q_proj_x = nn.Linear(dim, dim, bias=qkv_bias)
        self.k_proj_x = nn.Linear(dim, self.head_dim * self.num_kv_heads, bias=qkv_bias)
        self.v_proj_x = nn.Linear(dim, self.head_dim * self.num_kv_heads, bias=qkv_bias)
        self.gate_x = nn.Sequential(nn.Linear(dim, 2 * dim, bias=False), nn.Sigmoid())
        self.proj_x = nn.Linear(dim, dim)

        self.oneside = oneside
        self.k_proj_y = nn.Linear(dim, self.head_dim * self.num_kv_heads, bias=qkv_bias)
        self.v_proj_y = nn.Linear(dim, self.head_dim * self.num_kv_heads, bias=qkv_bias)
        if not self.oneside:
            self.q_proj_y = nn.Linear(dim, dim, bias=qkv_bias)
            self.gate_y = nn.Sequential(
                nn.Linear(dim, 2 * dim, bias=False), nn.Sigmoid()
            )
            self.proj_y = nn.Linear(dim, dim)

        if use_weight_norm:
            self.q_proj_x = nn.utils.parametrizations.weight_norm(self.q_proj_x)
            self.k_proj_x = nn.utils.parametrizations.weight_norm(self.k_proj_x)
            self.v_proj_x = nn.utils.parametrizations.weight_norm(self.v_proj_x)
            self.proj_x = nn.utils.parametrizations.weight_norm(self.proj_x)
            self.k_proj_y = nn.utils.parametrizations.weight_norm(self.k_proj_y)
            self.v_proj_y = nn.utils.parametrizations.weight_norm(self.v_proj_y)
            if not self.oneside:
                self.q_proj_y = nn.utils.parametrizations.weight_norm(self.q_proj_y)
                self.proj_y = nn.utils.parametrizations.weight_norm(self.proj_y)

    def forward(self, x, y):
        B, N_x, C = x.shape
        _, N_y, _ = y.shape

        q_x = self.q_proj_x(x).reshape(B, N_x, self.num_q_heads, self.head_dim)
        k_x = self.k_proj_x(x).reshape(B, N_x, self.num_kv_heads, self.head_dim)
        v_x = self.v_proj_x(x).reshape(B, N_x, self.num_kv_heads, self.head_dim)
        dtype = q_x.dtype

        k_y = self.k_proj_y(y).reshape(B, N_y, self.num_kv_heads, self.head_dim)
        v_y = self.v_proj_y(y).reshape(B, N_y, self.num_kv_heads, self.head_dim)
        if not self.oneside:
            q_y = self.q_proj_y(y).reshape(B, N_y, self.num_q_heads, self.head_dim)

        q_x = self.norm_layer(q_x).to(dtype=dtype)
        k_x = self.norm_layer(k_x).to(dtype=dtype)
        k_y = self.norm_layer(k_y).to(dtype=dtype)
        if not self.oneside:
            q_y = self.norm_layer(q_y).to(dtype=dtype)

        x_cross = flash_attn_func(q_x, k_y, v_y)
        x_cross = x_cross.reshape(B, N_x, C)

        x_self = flash_attn_func(q_x, k_x, v_x)
        x_self = x_self.reshape(B, N_x, C)

        x_gate = self.gate_x(x)
        x = (
            x_cross * x_gate[:, :, 0 : self.dim]
            + x_self * x_gate[:, :, self.dim : 2 * self.dim]
        )
        x = self.proj_x(x)

        if not self.oneside:
            y_cross = flash_attn_func(q_y, k_x, v_x)
            y_cross = y_cross.reshape(B, N_y, C)

            y_self = flash_attn_func(q_y, k_y, v_y)
            y_self = y_self.reshape(B, N_y, C)

            y_gate = self.gate_y(y)
            y = (
                y_cross * y_gate[:, :, 0 : self.dim]
                + y_self * y_gate[:, :, self.dim : 2 * self.dim]
            )
            y = self.proj_y(y)
            return x, y
        else:
            return x


class BlockMix(nn.Module):
    def __init__(
        self,
        dim,
        num_q_heads=32,
        num_kv_heads=2,
        mlp_ratio=4.0,
        qkv_bias=False,
        act_layer=nn.GELU,
        norm_layer=nn.LayerNorm,
        use_weight_norm=False,
    ):
        super().__init__()
        mlp_hidden_dim = int(dim * mlp_ratio)
        self.norm_x = norm_layer(dim, elementwise_affine=False)
        self.norm_y = norm_layer(dim, elementwise_affine=False)
        self.crs_attn = CrossAttention(
            dim,
            num_q_heads=num_q_heads,
            num_kv_heads=num_kv_heads,
            qkv_bias=qkv_bias,
            use_weight_norm=use_weight_norm,
            norm_layer=norm_layer,
        )
        self.mlp_x_1 = Mlp(
            in_features=dim,
            hidden_features=mlp_hidden_dim,
            act_layer=act_layer,
            use_weight_norm=use_weight_norm,
        )
        self.mlp_y_1 = Mlp(
            in_features=dim,
            hidden_features=mlp_hidden_dim,
            act_layer=act_layer,
            use_weight_norm=use_weight_norm,
        )

    def forward(self, x, y, image_num):
        # Cross attention between x and y
        x_res, y_res = self.crs_attn(self.norm_x(x), self.norm_y(y))
        x = x + x_res
        x = x + self.mlp_x_1(self.norm_x(x))
        y = y + y_res
        y = y + self.mlp_y_1(self.norm_y(y))

        return x, y


class BlockMixOneside(nn.Module):
    def __init__(
        self,
        dim,
        num_q_heads=32,
        num_kv_heads=2,
        mlp_ratio=4.0,
        qkv_bias=False,
        act_layer=nn.GELU,
        norm_layer=nn.LayerNorm,
        use_weight_norm=False,
    ):
        super().__init__()
        mlp_hidden_dim = int(dim * mlp_ratio)
        self.norm_x = norm_layer(dim, elementwise_affine=False)
        self.norm_y = norm_layer(dim, elementwise_affine=False)
        self.crs_attn = CrossAttention(
            dim,
            num_q_heads=num_q_heads,
            num_kv_heads=num_kv_heads,
            qkv_bias=qkv_bias,
            use_weight_norm=use_weight_norm,
            norm_layer=norm_layer,
            oneside=True,
        )
        self.mlp_x_1 = Mlp(
            in_features=dim,
            hidden_features=mlp_hidden_dim,
            act_layer=act_layer,
            use_weight_norm=use_weight_norm,
        )

    def forward(self, x, y):
        # Cross attention between x and y
        x_res = self.crs_attn(self.norm_x(x), self.norm_y(y))
        x = x + x_res
        x = x + self.mlp_x_1(self.norm_x(x))

        return x


def _make_fusion_block(features, size=None, has_residual=True, groups=1):
    return FeatureFusionBlock(
        features,
        nn.ReLU(inplace=True),
        deconv=False,
        bn=False,
        expand=False,
        align_corners=True,
        size=size,
        has_residual=has_residual,
        groups=groups,
    )


def _make_scratch(in_shape, out_shape, groups=1, expand=False):
    scratch = nn.Module()
    out_shape1 = out_shape
    out_shape2 = out_shape
    out_shape3 = out_shape
    if len(in_shape) >= 4:
        out_shape4 = out_shape

    if expand:
        out_shape1 = out_shape
        out_shape2 = out_shape * 2
        out_shape3 = out_shape * 4
        if len(in_shape) >= 4:
            out_shape4 = out_shape * 8

    scratch.layer1_rn = nn.Conv2d(
        in_shape[0],
        out_shape1,
        kernel_size=3,
        stride=1,
        padding=1,
        bias=False,
        groups=groups,
    )
    scratch.layer2_rn = nn.Conv2d(
        in_shape[1],
        out_shape2,
        kernel_size=3,
        stride=1,
        padding=1,
        bias=False,
        groups=groups,
    )
    scratch.layer3_rn = nn.Conv2d(
        in_shape[2],
        out_shape3,
        kernel_size=3,
        stride=1,
        padding=1,
        bias=False,
        groups=groups,
    )
    if len(in_shape) >= 4:
        scratch.layer4_rn = nn.Conv2d(
            in_shape[3],
            out_shape4,
            kernel_size=3,
            stride=1,
            padding=1,
            bias=False,
            groups=groups,
        )
    return scratch


class ResidualConvUnit(nn.Module):
    """Residual convolution module."""

    def __init__(self, features, activation, bn, groups=1):
        """Init.

        Args:
            features (int): number of features
        """
        super().__init__()

        self.bn = bn
        self.groups = groups
        self.conv1 = nn.Conv2d(
            features,
            features,
            kernel_size=3,
            stride=1,
            padding=1,
            bias=True,
            groups=self.groups,
        )
        self.conv2 = nn.Conv2d(
            features,
            features,
            kernel_size=3,
            stride=1,
            padding=1,
            bias=True,
            groups=self.groups,
        )

        self.norm1 = None
        self.norm2 = None

        self.activation = activation
        self.skip_add = nn.quantized.FloatFunctional()

    def forward(self, x):
        """Forward pass.

        Args:
            x (tensor): input

        Returns:
            tensor: output
        """

        out = self.activation(x)
        out = self.conv1(out)
        if self.norm1 is not None:
            out = self.norm1(out)

        out = self.activation(out)
        out = self.conv2(out)
        if self.norm2 is not None:
            out = self.norm2(out)

        return self.skip_add.add(out, x)


class FeatureFusionBlock(nn.Module):
    """Feature fusion block."""

    def __init__(
        self,
        features,
        activation,
        deconv=False,
        bn=False,
        expand=False,
        align_corners=True,
        size=None,
        has_residual=True,
        groups=1,
    ):
        """Init.

        Args:
            features (int): number of features
        """
        super(FeatureFusionBlock, self).__init__()

        self.deconv = deconv
        self.align_corners = align_corners
        self.groups = groups
        self.expand = expand
        out_features = features
        if self.expand:
            out_features = features // 2

        self.out_conv = nn.Conv2d(
            features,
            out_features,
            kernel_size=1,
            stride=1,
            padding=0,
            bias=True,
            groups=self.groups,
        )

        if has_residual:
            self.resConfUnit1 = ResidualConvUnit(
                features, activation, bn, groups=self.groups
            )

        self.has_residual = has_residual
        self.resConfUnit2 = ResidualConvUnit(
            features, activation, bn, groups=self.groups
        )

        self.skip_add = nn.quantized.FloatFunctional()
        self.size = size

    def forward(self, *xs, size=None):
        """Forward pass.

        Returns:
            tensor: output
        """
        output = xs[0]

        if self.has_residual:
            res = self.resConfUnit1(xs[1])
            output = self.skip_add.add(output, res)

        output = self.resConfUnit2(output)

        if (size is None) and (self.size is None):
            modifier = {"scale_factor": 2}
        elif size is None:
            modifier = {"size": self.size}
        else:
            modifier = {"size": size}

        output = custom_interpolate(
            output, **modifier, mode="bilinear", align_corners=self.align_corners
        )
        output = self.out_conv(output)

        return output


def custom_interpolate(
    x: torch.Tensor,
    size=None,
    scale_factor=None,
    mode: str = "bilinear",
    align_corners: bool = True,
) -> torch.Tensor:
    """
    Custom interpolate to avoid INT_MAX issues in nn.functional.interpolate.
    """
    if size is None:
        size = (int(x.shape[-2] * scale_factor), int(x.shape[-1] * scale_factor))

    INT_MAX = 1610612736

    input_elements = size[0] * size[1] * x.shape[0] * x.shape[1]

    if input_elements > INT_MAX:
        chunks = torch.chunk(x, chunks=(input_elements // INT_MAX) + 1, dim=0)
        interpolated_chunks = [
            nn.functional.interpolate(
                chunk, size=size, mode=mode, align_corners=align_corners
            )
            for chunk in chunks
        ]
        x = torch.cat(interpolated_chunks, dim=0)
        return x.contiguous()
    else:
        return nn.functional.interpolate(
            x, size=size, mode=mode, align_corners=align_corners
        )
